// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float humidityLevel;
float methaneLevel;
float temperatureLevel;
CloudColoredLight rgbLed;
bool buzzerState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidityLevel, READ, 3 * SECONDS, NULL);
  ArduinoCloud.addProperty(methaneLevel, READ, 3 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatureLevel, READ, 3 * SECONDS, NULL);
  ArduinoCloud.addProperty(rgbLed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(buzzerState, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
